package mad.rpg.game.states;

public enum StateType {
    EMPTY_STATE, GAME_ENDING_STATE, CHARACTER_LISTING_STATE, CHARACTER_CREATING_STATE, GAME_BEGINNING_STATE, EXPLORATION_STATE, BATTLE_STATE, GAME_BUILDING_STATE
}
