package mad.rpg.game.events;

public enum EventType {
    CHARACTER_SELECTED, CHARACTER_CREATED, CHARACTER_NOT_CREATED, GAME_STARTED, CHARACTER_CREATION_REQUEST, GAME_BUILT, ENEMY_FOUND_IN_ROOM, ENEMY_DEFEATED, PLAYER_DEFEATED, PLAYER_RAN_AWAY, EXIT_REQUESTED
}
